spring:
  application:
    name: User-Manage-back
  datasource: #数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: 123456
  servlet:
    multipart:
      max-request-size: 15MB #改为自己的想要的
      max-file-size: 10MB #上传图片的大小
      enabled: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #数据库我使用的是下划线,程序中用的是驼峰,实现数据库下划线字段与实体中的驼峰属性映射
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    max-swallow-size: 100MB #重要的一行，修改tomcat的吞吐量
file:
  uploadFolder: D:/project/user-manage-system/User-Manage-back/src/main/resources/static/images/
  staticAccessPath: /file/**
  request: http://localhost:8000/api/file/


